Update jenkinsfile

diff --git a/Final/jenkinsfile b/Final/jenkinsfile
--- a/Final/jenkinsfile
+++ b/Final/jenkinsfile
@@ -13,13 +13,12 @@ pipeline {
             }
             steps {
                 git url: 'https://github.com/AlexeyRusak/word-cloud-generator'
-               // sh '''
-               sh 'make'
-                //make lint && make test
-                // if [ $? -ne 0 ];
-                 //   then
-                 //       echo "Test error"
-                  //      exit 1
+                sh '''
+                make lint && make test
+                 if [ $? -ne 0 ];
+                    then
+                        echo "Test error"
+                        exit 1
                     fi
                 export GOPATH=$WORKSPACE/go
                 export PATH="$PATH:$(go env GOPATH)/bin"               
