Update jenkinsfile

diff --git a/Final/jenkinsfile b/Final/jenkinsfile
--- a/Final/jenkinsfile
+++ b/Final/jenkinsfile
@@ -15,10 +15,10 @@ pipeline {
                 git url: 'https://github.com/AlexeyRusak/word-cloud-generator/'
                 sh '''
                 make lint && make test
-                 //if [ $? -ne 0 ];
-                 //   then
-                 //       echo "Test error"
-                  //      exit 1
+                 if [ $? -ne 0 ];
+                    then
+                        echo "Test error"
+                        exit 1
                     fi
                 export GOPATH=$WORKSPACE/go
                 export PATH="$PATH:$(go env GOPATH)/bin"               
